# Generated by Django 2.0.4 on 2018-07-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphRun',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('content_parsed', models.TextField()),
                ('run_start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.Graph')),
            ],
        ),
        migrations.CreateModel(
            name='GraphRunState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField()),
                ('state', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='graphrun',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.GraphRunState'),
        ),
    ]
