# Generated by Django 2.0.4 on 2018-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180703_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphrun',
            old_name='graph_id',
            new_name='graph',
        ),
        migrations.RenameField(
            model_name='graphrun',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='graphrunstate',
            name='id',
        ),
        migrations.AlterField(
            model_name='graphrunstate',
            name='state_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
