# Generated by Django 2.0.4 on 2018-12-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180703_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphrun',
            name='content_parsed',
        ),
    ]
