# Generated by Django 2.0.4 on 2018-12-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_graphrun_content_parsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphrun',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='graphrun',
            name='run_start',
        ),
    ]
