# Generated by Django 2.0.4 on 2018-12-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181209_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphrun',
            name='graph_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
